# ═══════════════════════════════════════════════════════════════════════════════
# REUSABLE FOR: Vows & Vedas wedding chatbot   |   SAFE COPY (no secrets)
# SOURCE: MCI-GeTS-Chatbot/data_pipeline/make_website_chunks.py
#
# WHAT IT DOES: turns website pages into clean, overlapping text chunks ready for
#   embedding + indexing. The chunking logic (split_into_chunks, overlap, MIN_WORDS,
#   BAD_PATTERNS junk filter) is fully domain-agnostic — REUSE AS-IS.
#
# HOW TO REUSE for weddings:
#   - SOURCE: instead of scraped_pages.json, feed your wedding content. NOTE: the wedding
#     site keeps venues/services/FAQ HARDCODED in React components (src/app/**) — first
#     extract that content to JSON, then chunk it here.
#   - TODO(wedding): DESTINATION_KEYWORDS is a travel list — replace with wedding cities +
#     venue types so detect_destination() tags chunks correctly.
#   - SKIP_TYPES / BAD_PATTERNS: keep; just tune the wording for wedding pages.
# ═══════════════════════════════════════════════════════════════════════════════
"""
Website → Chunks Converter
--------------------------
Reads data/raw/scraped_pages.json (generated by ingestion/scraper/scraper.py)
and converts to website_chunks.json in the same format as packages_chunks.json,
ready for the /admin/ingest endpoint.

Run from data_pipeline/:
    python make_website_chunks.py

Requires scraped_pages.json to exist first:
    cd <project_root>
    python ingestion/scraper/scraper.py
"""

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT             = Path(__file__).parent.parent
SCRAPED_PATH     = ROOT / "data" / "raw" / "scraped_pages.json"
OUTPUT_PATH      = Path(__file__).parent / "website_chunks.json"
CHUNK_SIZE_WORDS = 250
CHUNK_OVERLAP    = 40
MIN_WORDS        = 40

# Pages that add no travel value
SKIP_TYPES = {"contact", "about"}
BAD_PATTERNS = [
    r"connect you to",
    r"share your (details|contact)",
    r"leave your message",
    r"we will get back",
    r"may i have your name",
    r"cookie",
    r"privacy policy",
    r"terms (and|&) conditions",
    r"copyright",
    r"all rights reserved",
]

# TODO(wedding): replace with wedding cities + venue types (Udaipur, Jaipur, Jodhpur,
# Goa, Kochi… + palace / heritage / beach / banquet / lawn) so chunks tag correctly.
DESTINATION_KEYWORDS = [
    "kerala", "rajasthan", "goa", "kashmir", "ladakh", "himachal",
    "uttarakhand", "assam", "meghalaya", "arunachal", "karnataka",
    "tamil nadu", "gujarat", "maharashtra", "odisha", "andaman",
    "delhi", "agra", "jaipur", "jodhpur", "udaipur", "jaisalmer",
    "varanasi", "manali", "leh", "dharamshala", "mumbai", "kochi",
    "munnar", "bangalore", "chennai", "ranthambore", "rishikesh",
    "amritsar", "bhutan", "nepal", "sri lanka", "golden triangle",
    "north india", "south india", "northeast",
]


def detect_destination(text: str) -> str:
    text_lower = text.lower()
    for dest in DESTINATION_KEYWORDS:
        if dest in text_lower:
            return dest.title()
    return "India"


def is_bad(text: str) -> bool:
    text_lower = text.lower()
    return any(re.search(p, text_lower) for p in BAD_PATTERNS)


def split_into_chunks(text: str) -> list[str]:
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = min(start + CHUNK_SIZE_WORDS, len(words))
        chunk_words = words[start:end]
        if len(chunk_words) >= MIN_WORDS:
            chunks.append(" ".join(chunk_words))
        start += CHUNK_SIZE_WORDS - CHUNK_OVERLAP
    return chunks


def main():
    if not SCRAPED_PATH.exists():
        print(f"[error] {SCRAPED_PATH} not found.")
        print("Run this first from the project root:")
        print("  python ingestion/scraper/scraper.py")
        sys.exit(1)

    with open(SCRAPED_PATH, encoding="utf-8") as f:
        pages = json.load(f)

    print(f"Loaded {len(pages)} scraped pages")

    chunks = []
    skipped = 0

    for page in pages:
        page_type = page.get("page_type", "general")
        if page_type in SKIP_TYPES:
            skipped += 1
            continue

        title = page.get("title", "").strip()
        url = page.get("url", "")
        meta = page.get("meta_description", "").strip()
        main = page.get("main_content", "").strip()
        headings = " ".join(page.get("headings", []))

        # Build full content from all available fields
        content = "\n".join(filter(None, [meta, headings, main])).strip()

        if not content or len(content.split()) < MIN_WORDS:
            skipped += 1
            continue

        if is_bad(content):
            skipped += 1
            continue

        destination = detect_destination(f"{title} {content}")
        text_chunks = split_into_chunks(content)

        for i, chunk_text in enumerate(text_chunks):
            if is_bad(chunk_text):
                continue
            full_text = f"Page: {title}\nType: {page_type}\nURL: {url}\n\n{chunk_text}"
            chunk_id = hashlib.sha256(full_text.encode("utf-8")).hexdigest()
            chunks.append({
                "chunk_id": chunk_id,
                "package_name": title,
                "primary_destination": destination,
                "chunk_type": "website",
                "page_type": page_type,
                "url": url,
                "text": full_text,
            })

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(chunks, f, ensure_ascii=False, indent=2)

    print(f"\nDone.")
    print(f"  Pages processed : {len(pages) - skipped}")
    print(f"  Pages skipped   : {skipped}")
    print(f"  Chunks produced : {len(chunks)}")
    print(f"  → {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
